# Generated by Django 5.2.6 on 2025-09-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(choices=[('1', 'Kluswerk Algemeen'), ('2', 'Klus en Reparatiewerk'), ('3', 'Timmerwerk'), ('4', 'Elektrisch Werk'), ('5', 'Loodgieterij')], max_length=2)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created'],
            },
        ),
    ]
