# Generated by Django 5.2.6 on 2025-09-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='justcodeworks@gmail.com', max_length=254)),
                ('whatsapp', models.CharField(blank=True, default='+31687111289', max_length=32)),
                ('phone_display', models.CharField(blank=True, default='06 87111289', max_length=32)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('1', 'Keuken'), ('2', 'Badkamer'), ('3', 'Vloeren'), ('4', 'Kluswerk Algemeen'), ('5', 'Klus en Reparatiewerk'), ('6', 'Timmerwerk'), ('7', 'Elektrisch Werk'), ('8', 'Loodgieterij')], max_length=2),
        ),
    ]
