# Generated by Django 5.0.7 on 2025-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactsubmission_sitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=32)),
                ('daily_budget', models.IntegerField(blank=True, null=True)),
                ('objective', models.CharField(blank=True, max_length=64)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_stop', models.DateField(blank=True, null=True)),
                ('spend', models.FloatField(default=0.0)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=64, unique=True)),
                ('form_id', models.CharField(max_length=64)),
                ('created_time', models.DateTimeField()),
                ('data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_post_id', models.CharField(max_length=128, unique=True)),
                ('created_time', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('media_url', models.URLField(blank=True, max_length=500)),
                ('reactions', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='FacebookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=64)),
                ('page_name', models.CharField(blank=True, max_length=255)),
                ('ad_account_id', models.CharField(blank=True, max_length=64)),
                ('app_id', models.CharField(blank=True, max_length=64)),
                ('app_secret', models.CharField(blank=True, max_length=128)),
                ('user_access_token', models.TextField(blank=True)),
                ('page_access_token', models.TextField(blank=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('connected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Facebook settings',
                'verbose_name_plural': 'Facebook settings',
            },
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('1', 'Keuken'), ('2', 'Badkamer'), ('3', 'Vloeren'), ('4', 'Kluswerk Algemeen'), ('5', 'Klus en Reparatiewerk'), ('6', 'Timmerwerk'), ('7', 'Elektrisch Werk'), ('8', 'Loodgieterij'), ('9', 'Stukwerk')], max_length=2),
        ),
    ]
