# Generated by Django 5.0.7 on 2025-09-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facebookcampaign_facebooklead_facebookpost_and_more'),
    ]

    operations = []
