# Generated by Django 5.0.7 on 2025-09-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('path', models.CharField(blank=True, max_length=255, unique=True)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('menu_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['menu_order', 'title'],
            },
        ),
    ]
